---
title: Opmerkingen en feedback in Scratch
hero_image: images/banner.png
description: Opmerkingen en feedback in Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-11-27"
steps:
  - title: Opmerkingen en feedback in Scratch
