title: Comments and feedback in Scratch
hero_image: images/banner.png
description: Comments-feedback-Scratch description
version: 4
listed: false
copyedit: false
last_tested: "2020-11-27"
steps:
  - title: Introduction
