---
title: Izimvo kunye nengxelo kuScratch
hero_image: images/banner.png
description: Izimvo kunye nengxelo kuScratch
version: 4
listed: false
copyedit: false
last_tested: '2020-11-27'
steps:
  - 
    title: Izimvo kunye nengxelo kuScratch
