---
title: Comments and feedback in Scratch
hero_image: images/banner.png
description: Comments and feedback in Scratch
version: 4
listed: false
copyedit: false
last_tested: '2020-11-27'
steps:
  - 
    title: Comments and feedback in Scratch
