---
title: Komentari i povratne informacije u Scratchu
hero_image: images/banner.png
description: Komentari i povratne informacije u Scratchu
version: 4
listed: false
copyedit: false
last_tested: '2020-11-27'
steps:
  - title: Komentari i povratne informacije u Scratchu
