---
title: Sylwadau ac adborth yn Scratch
hero_image: images/banner.png
description: Sylwadau ac adborth yn Scratch
version: 4
listed: false
copyedit: false
last_tested: '2020-11-27'
steps:
  - 
    title: Sylwadau ac adborth yn Scratch
