---
title: Kommentare und Feedback in Scratch
hero_image: images/banner.png
description: Kommentare und Feedback in Scratch
version: 4
listed: false
copyedit: false
last_tested: '2020-11-27'
steps:
  - title: Kommentare und Feedback in Scratch
