---
title: Comentários e opinião no Scratch
hero_image: images/banner.png
description: Comentários e opinião no Scratch
version: 4
listed: false
copyedit: false
last_tested: '2020-11-27'
steps:
- title: Comentários e opinião no Scratch
