---
title: Komentáře a zpětná vazba ve Scratch
hero_image: images/banner.png
description: Komentáře a zpětná vazba ve Scratch
version: 4
listed: false
copyedit: false
last_tested: '2020-11-27'
steps:
  - 
    title: Komentáře a zpětná vazba ve Scratch
