---
title: Comentarios y retroalimentación en Scratch
hero_image: images/banner.png
description: Comentarios y retroalimentación en Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-11-27"
steps:
  - title: Comentarios y retroalimentación en Scratch
