---
title: Komentarze w Scratch
hero_image: images/banner.png
description: Komentarze w Scratch
version: 4
listed: false
copyedit: false
last_tested: '2020-11-27'
steps:
  - title: Komentarze w Scratch
