---
title: Kommentarer och feedback i Scratch
hero_image: images/banner.png
description: Kommentarer och feedback i Scratch
version: 4
listed: false
copyedit: false
last_tested: '2020-11-27'
steps:
  - title: Kommentarer och feedback i Scratch
