---
title: Commentaires et feedback dans Scratch
hero_image: images/banner.png
description: Commentaires et feedback dans Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-11-27"
steps:
  - 
    title: Commentaires et feedback dans Scratch
